version: '3'

services:
  backend:
    build:
      context: ./DataMang_server
      dockerfile: Dockerfile
    image: "vickym03/upload :server"
    ports:
      - 5000:5000
    environment:
      - CHOKIDAR_USEPOLLING=true  
    stdin_open: true 


  frontend:
    build:
      context: ./DataMang_client
      dockerfile: Dockerfile
    image: "vickym03/upload:client"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true  
    stdin_open: true 
    links:
      - "backend"


